# Generated by Django 5.2.3 on 2025-06-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moderationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationresult',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_result', to='reviews.review'),
        ),
    ]
