# Generated by Django 5.2.3 on 2025-06-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_moderationresult_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='non_spam_probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='spam_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
