# Generated by Django 5.2.3 on 2025-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_moderationresult_is_spam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('moderation', 'Moderation'), ('spam_detection', 'Spam Detection')], max_length=20)),
                ('input_text', models.TextField(help_text='The input that caused the error')),
                ('error_message', models.TextField(help_text='The actual error message')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code returned by the service', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Service Error',
                'verbose_name_plural': 'AI Service Errors',
                'ordering': ['-timestamp'],
            },
        ),
    ]
